name = "systemfehler-api-worker"
main = "cloudflare-workers/index.mjs"
compatibility_date = "2026-03-08"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "systemfehler-db"
database_id = "318e633f-b1da-4fb3-9ce7-a0bc2ccf3160"

[triggers]
# crons = ["0 0 * * *"]