#!/usr/bin/env python3
"""Generate a D1 SQL seed file from the current snapshot corpus.

Usage:
    python scripts/generate_d1_seed_sql.py --output cloudflare-pages/d1/seed_entries.generated.sql
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DOMAINS = ["benefits", "aid", "tools", "organizations", "contacts"]
MAX_STRING_LENGTH = 12000
MAX_ARRAY_ITEMS = 100


def sql_string(value: object) -> str:
    if value is None:
        return "NULL"
    if not isinstance(value, str):
        value = str(value)
    return "'" + value.replace("'", "''") + "'"


def load_entries(snapshot_path: Path) -> list[dict]:
    data = json.loads(snapshot_path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        nested = data.get("entries")
        if isinstance(nested, list):
            data = nested
    if not isinstance(data, list):
        raise ValueError(f"{snapshot_path} does not contain a JSON array")
    return [entry for entry in data if isinstance(entry, dict) and entry.get("id")]


def compact_value(value: object) -> object:
    if isinstance(value, str):
        if len(value) <= MAX_STRING_LENGTH:
            return value
        return value[:MAX_STRING_LENGTH].rstrip() + "\n\n[Inhalt fuer D1/Pages gekuerzt]"
    if isinstance(value, list):
        return [compact_value(item) for item in value[:MAX_ARRAY_ITEMS]]
    if isinstance(value, dict):
        compacted: dict[str, object] = {}
        for key, item in value.items():
            compacted[key] = compact_value(item)
        return compacted
    return value


def entry_updated_at(entry: dict) -> str | None:
    return (
        entry.get("updated_at")
        or entry.get("updatedAt")
        or entry.get("lastSeen")
        or entry.get("last_seen")
        or entry.get("firstSeen")
        or entry.get("first_seen")
    )


def build_insert(domain: str, entry: dict) -> str:
    compact_entry = compact_value(entry)
    entry_json = json.dumps(compact_entry, ensure_ascii=False, separators=(",", ":"))
    return (
        "INSERT INTO entries (id, domain, url, status, title_de, updated_at, entry_json) VALUES "
        f"({sql_string(entry.get('id'))}, {sql_string(domain)}, {sql_string(entry.get('url'))}, "
        f"{sql_string(entry.get('status'))}, {sql_string(entry.get('title_de') or entry.get('title', {}).get('de') if isinstance(entry.get('title'), dict) else entry.get('title_de'))}, "
        f"{sql_string(entry_updated_at(entry))}, {sql_string(entry_json)}) "
        "ON CONFLICT(id) DO UPDATE SET "
        "domain=excluded.domain, url=excluded.url, status=excluded.status, "
        "title_de=excluded.title_de, updated_at=excluded.updated_at, entry_json=excluded.entry_json;"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate D1 seed SQL from snapshot entries")
    parser.add_argument("--output", required=True, help="Path to the SQL file to create")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = repo_root / output_path

    lines: list[str] = [
        "-- Generated by scripts/generate_d1_seed_sql.py",
        "DELETE FROM entries;",
    ]

    total = 0
    for domain in DOMAINS:
        snapshot_path = repo_root / "data" / domain / "entries.json"
        entries = load_entries(snapshot_path)
        lines.append(f"-- {domain}: {len(entries)} entries")
        for entry in entries:
            lines.append(build_insert(domain, entry))
        total += len(entries)

    lines.append(f"-- total entries: {total}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {total} entries to {output_path}")


if __name__ == "__main__":
    main()
